### ISSUE TITLE
Unnamed object parameters

### ISSUE THREAD

**Issue by alexeagle** [angular/sickle#95]
```
index (1) must be less than size (1)
  Node(PARAM_LIST): /javascript/angular2/github/modules/angular2/src/core/di/provider.js:69:15
    constructor(token, { useClass, useValue, useExisting, useFactory, deps, multi }) {
  Parent(FUNCTION ):/javascript/angular2/github/modules/angular2/src/core/di/provider.js:69:4
    constructor(token, { useClass, useValue, useExisting, useFactory, deps, multi }) {

	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1295)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1277)
	at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:41)
```

`javascript/angular2/github/modules/angular2/src/core/di/provider.js` looks like

```
/**
     * @param token
     * @param { ?} {useClass, useValue, useExisting, useFactory, deps, multi}
     */
    constructor(token, { useClass, useValue, useExisting, useFactory, deps, multi }) {
```

I don't think that name for parameter 2 is legal.

This is the next blocker for compiling angular2 with closure compiler.

**Comment by martine** [comment]
Hmm, this looks like ES6 destructuring.  I checked that that works for functions and constructors.  This code even works:
```js
class Foo {
 /**
  * @param token
  * @param { ?} {y, z, a, b}
  */
 constructor(token, {y, z, a, b}) {
   this.token = token;
   this.y = y;
   this.z = z;
 }
}
let foo = new Foo(3, {y:4, z:5, a:6, b:7});
console.log(foo);
```

The other weird thing here is that "token" is untyped.  In the original source it's:
```js
  constructor(token, {useClass, useValue, useExisting, useFactory, deps, multi}: {
    useClass?: Type,
    useValue?: any,
    useExisting?: any,
    useFactory?: Function,
    deps?: Object[],
    multi?: boolean
  }) {
```
so maybe it's getting an implicit any?

**Comment by alexeagle** [comment]
I can work on this one, I'll start looking. Let me know if you're already on it.

**Comment by martine** [comment]
If you can come up with a test case that the JS compiler rejects, I could swoop in and make the appropriate sickle fix.

**Comment by alexeagle** [comment]
repro and workaround here: https://github.com/angular/sickle/commit/bb806ec7f50a64231e2b2f253dd4b60989b09172
